FROM centos:7.9.2009 AS builder-base

LABEL maintainer="Michal Lazniewski <mlazniewski@pzh.gov.pl>"

# Workaround for missing repository
# https://serverfault.com/questions/904304/could-not-resolve-host-mirrorlist-centos-org-centos-7
COPY third-party/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo
RUN yum install -y epel-release
RUN yum install -y tar bzip2 make gcc gcc-c++ libstdc++-static zlib-devel vim which wget python-devel python2-pip xz-devel bzip2-devel libcurl-devel ncurses-devel
## END

## MANTA
FROM builder-base AS builder-manta
ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++
RUN mkdir -p /opt/docker
WORKDIR /opt/docker
RUN wget https://github.com/Illumina/manta/releases/download/v1.6.0/manta-1.6.0.release_src.tar.bz2
RUN tar -xjf manta-1.6.0.release_src.tar.bz2
RUN mkdir -p /opt/docker/manta-1.6.0.release_src/build
WORKDIR /opt/docker/manta-1.6.0.release_src/build
RUN ../configure --jobs=$(nproc) --prefix=/opt/docker/manta
RUN make -j 4 install
## End

## Htslib v1.17
FROM builder-base AS builder-htslib
WORKDIR /opt/docker
RUN wget https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
RUN tar -xf htslib-1.17.tar.bz2
WORKDIR /opt/docker/htslib-1.17
RUN ./configure --prefix=/opt/docker/htslib
RUN make -j $(nproc) && make install
ENV LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
## End

## Bcftools v1.17
FROM builder-base AS builder-bcftools
WORKDIR /opt/docker
RUN wget https://github.com/samtools/bcftools/releases/download/1.17/bcftools-1.17.tar.bz2
RUN tar -xf bcftools-1.17.tar.bz2
WORKDIR /opt/docker/bcftools-1.17
RUN ./configure --prefix=/opt/docker/bcftools
RUN make -j $(nproc) && make install
## End

## Samtools v1.17
FROM builder-base AS builder-samtools
WORKDIR /opt/docker
RUN wget https://github.com/samtools/samtools/releases/download/1.17/samtools-1.17.tar.bz2
RUN tar -xf samtools-1.17.tar.bz2
WORKDIR /opt/docker/samtools-1.17
RUN ./configure --prefix=/opt/docker/samtools
RUN make -j $(nproc) && make install
## End

## Python packages
FROM builder-base AS builder-python-packages
RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | python # Vide: https://stackoverflow.com/questions/16370583/pip-issue-installing-almost-any-library
RUN pip install numpy==1.16.5
RUN pip install biopython==1.76

CMD ["/bin/bash"]

FROM centos:7.9.2009 AS manta

# Workaround for missing repository
# https://serverfault.com/questions/904304/could-not-resolve-host-mirrorlist-centos-org-centos-7
COPY third-party/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo
RUN yum install -y epel-release
RUN yum install -y tar python2-pip

WORKDIR /opt/docker
ADD third-party/mafft/mafft-7.520-gcc_fc6.x86_64.rpm /opt/docker
RUN rpm -Uvh mafft-7.520-gcc_fc6.x86_64.rpm && \
    rm -f /opt/docker/mafft-7.520-gcc_fc6.x86_64.rpm

## Kopiowanie wymaganych plikow
RUN mkdir -p /SARS-CoV2/ 
COPY data/sarscov2/genome /SARS-CoV2/genome
WORKDIR /

COPY --from=builder-manta /opt/docker/manta /opt/docker/manta
COPY --from=builder-htslib /opt/docker/htslib /opt/docker/htslib
COPY --from=builder-bcftools /opt/docker/bcftools /opt/docker/bcftools
COPY --from=builder-samtools /opt/docker/samtools /opt/docker/samtools
COPY --from=builder-python-packages /usr/lib64/python2.7/site-packages /usr/lib64/python2.7/site-packages/
COPY data/sarscov2/genome/ /home/data/sarscov2/genome
COPY bin /home/bin

ENV PATH="/home/bin/common:/home/bin/sarscov2:/home/bin/infl:/opt/docker/manta/bin:/opt/docker/htslib/bin:/opt/docker/bcftools/bin:/opt/docker/samtools/bin:$PATH"
ENV LD_LIBRARY_PATH="/opt/docker/manta/lib:/opt/docker/htslib/lib:/opt/docker/bcftools/lib:/opt/docker/samtools/lib:$LD_LIBRARY_PATH"
ENV GENOME_ID="MN908947.3"
ENV GENOME_FASTA="/home/data/sarscov2/genome/sarscov2.fasta"
## END

CMD ["/bin/bash"]
